name: Rperform Benchmarks (Comment)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Rperform Benchmarks (Receive)"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - uses: EngineerDanny/Rperform/actions/comment@github-actions
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}